using MyFireNumber.Core.Calculations;

namespace MyFireNumber.Tests.Calculations;

/// <summary>
/// Parity fixtures. Every expected value in this file was generated by running the shipped
/// TypeScript implementation (<c>web/src/utils/deferredCompensation.ts</c>) directly with
/// <c>node --experimental-strip-types</c>, not by reading the C# output back. The web app has no
/// test runner, so these fixtures are the only thing preventing the two front ends from silently
/// diverging. If one of these fails, re-run the TypeScript module before changing the expectation.
/// </summary>
public class DeferredCompensationParityTests
{
    [Fact]
    public void ShippedDefaultScenario_MatchesTypeScriptImplementation()
    {
        var result = DeferredCompensationCalculator.Calculate(DeferredCompensationDraft.Default.ToInputs(2024));

        Assert.Equal(800_000, result.CurrentBalance);

        // Re-pinned for issue #56, which changed what the shipped defaults do rather than how they
        // are computed. Every value below was regenerated by running the updated TypeScript module
        // under `node --experimental-strip-types`, as the class comment requires.
        //
        // Before, the default scenario told a first-time visitor their plan failed in all 36
        // retirement years and then drew a chart ending on $4,623,220 they never spent. Both
        // statements came from the same cause: a capped withdrawal is min(cap, need), so once the
        // 4% cap bound, the projection stopped reading `need` at all.
        //
        //   BalanceAtSemiRetirement  1,798,250 -> 1,730,284  (ages 55-59 now fund themselves in
        //                                                     full from savings instead of leaving
        //                                                     two thirds of each year unpaid)
        //   FirstYearIncome             39,547 -> 107,513    (age 55 needs ~107,514 of inflated
        //                                                     spending; income used to be throttled
        //                                                     to 4% of the one reachable account
        //                                                     plus part-time pay, and now meets it)
        //   FirstYearSurplus           -67,967 -> 0          (the same year, now covered)
        //   EndingBalance            4,623,220 -> 0          (the money is finally spent)
        //   FundedYears / YearsFullyCovered  0 -> 21         (ages 55-75 covered)
        //   FirstShortfallAge               55 -> 76         (both accounts drain at 76)
        //
        // The result is coherent in a way the old one was not: the plan is funded until the money
        // runs out, and it runs out exactly when the balance reaches zero.
        Assert.Equal(1_730_284, result.BalanceAtSemiRetirement);
        Assert.Equal(107_513, result.FirstYearIncome);
        Assert.Equal(0, result.FirstYearSurplus);
        Assert.Equal(0, result.EndingBalance);
        Assert.Equal(21, result.FundedYears);
        Assert.Equal(21, result.YearsFullyCovered);
        Assert.Equal(76, result.FirstShortfallAge);

        // The projection array spans ages 45-90 (46 entries) but retirement is only 36 years
        // (55-90). MAUI previously divided by the projection count, overstating the denominator.
        Assert.Equal(46, result.Projections.Count);
        Assert.Equal(36, result.RetirementYears);
    }

    [Fact]
    public void DeferredCompensationScenario_MatchesTypeScriptImplementation()
    {
        var result = DeferredCompensationCalculator.Calculate(DeferredScenario());

        Assert.Equal(3_484_288, result.BalanceAtSemiRetirement);
        Assert.Equal(159_954, result.FirstYearIncome);
        Assert.Equal(39_001, result.FirstYearSurplus);
        Assert.Equal(4_929_176, result.EndingBalance);
        Assert.Equal(31, result.FundedYears);
        Assert.Equal(31, result.YearsFullyCovered);
        Assert.Equal(31, result.RetirementYears);
        Assert.Null(result.FirstShortfallAge);
    }

    [Fact]
    public void DeferredPayout_RisesWithCreditedEarningsAndFullyDistributes()
    {
        var result = DeferredCompensationCalculator.Calculate(DeferredScenario());
        var finalPayoutYear = result.Projections.Single(point => point.Age == 69);

        Assert.Equal(339_951, finalPayoutYear.DeferredIncome);
        Assert.Equal(113_317, finalPayoutYear.WithdrawalTaxes);

        // The payout window is ages 60-69, so the account must be exactly empty at 69 - nothing
        // may be stranded, because deferred accounts are never reachable by gap withdrawals.
        Assert.Equal(0, finalPayoutYear.Balances["def"]);
        Assert.Equal(0, result.Projections.Single(point => point.Age == 70).Balances["def"]);
    }

    private static DeferredCompensationInputs DeferredScenario() => new(
        CurrentAge: 50,
        SemiRetirementAge: 60,
        PlanThroughAge: 90,
        AnnualExpenses: 90_000,
        InflationRate: 0.03,
        Accounts:
        [
            new RetirementAccount("def", "Deferred comp", RetirementAccountType.Deferred, 800_000, 50_000, 0.06, 60, 0, 10),
            new RetirementAccount("401k", "401(k)", RetirementAccountType.Traditional, 600_000, 23_500, 0.07, 60, 0.2, 1)
        ],
        IncomeSources: [new RetirementIncomeSource("ss", "Social Security", 30_000, 67, 120, 0, true, 0.25)],
        AdditionalExpenses: [],
        WithdrawOnlyAfterRetirement: true,
        ReinvestSurplus: true,
        CurrentYear: 2024);
}
